/* Run against Chrome --remote-debugging-port=9223 and a disposable ODE database. */
const http = require('http');
const get = url => new Promise((resolve, reject) => http.get(url, r => {
  let body = ''; r.on('data', c => body += c); r.on('end', () => resolve(JSON.parse(body)));
}).on('error', reject));
const sleep = ms => new Promise(r => setTimeout(r, ms));

(async () => {
  const appUrl=process.argv[2]||'http://127.0.0.1:8876',debugPort=process.argv[3]||'9223';
  const pages = await get(`http://127.0.0.1:${debugPort}/json`);
  const page = pages.find(x => x.type === 'page' && x.url.startsWith(appUrl));
  if (!page) throw new Error('ODE page not found');
  const ws = new WebSocket(page.webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
  let id = 0; const pending = new Map();
  const runtimeErrors = [];
  const resourceErrors = [];
  const apiErrors = [];
  const httpErrors = [];
  ws.onmessage = event => {
    const m = JSON.parse(event.data);
    if (m.method === 'Runtime.exceptionThrown') runtimeErrors.push(m.params.exceptionDetails.exception?.description || m.params.exceptionDetails.text);
    if (m.method === 'Log.entryAdded' && ['error', 'warning'].includes(m.params.entry.level)) runtimeErrors.push(m.params.entry.text);
    if (m.method === 'Network.loadingFailed') resourceErrors.push(`${m.params.type}: ${m.params.errorText}`);
    if (m.method === 'Network.responseReceived' && m.params.response.status >= 400) {
      httpErrors.push(`${m.params.response.status}: ${m.params.response.url}`);
      if (m.params.response.status >= 500) apiErrors.push(`${m.params.response.status}: ${m.params.response.url}`);
    }
    if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); }
  };
  const send = (method, params = {}) => new Promise((resolve,reject) => { const n = ++id,t=setTimeout(()=>{pending.delete(n);reject(Error(`CDP timeout: ${method}`))},5000);pending.set(n,m=>{clearTimeout(t);resolve(m)});ws.send(JSON.stringify({id:n, method, params})); });
  await send('Runtime.enable'); await send('Log.enable'); await send('Network.enable');
  const visited = {odeHome:false,warehouse:false,receipt:false,issue:false,balance:false,history:false,reports:false,profile:false,administration:false,globalSearch:false,reloadAndBack:false};
  const evaluate = async expression => {
    const m = await send('Runtime.evaluate', {expression, awaitPromise:true, returnByValue:true});
    if (m.result?.exceptionDetails) throw new Error(m.result.exceptionDetails.exception?.description||m.result.exceptionDetails.text);
    return m.result?.result?.value;
  };
  const waitFor = async expression => { for (let i=0;i<50;i++) { if (await evaluate(expression)) return; await sleep(100); } throw new Error(`Timeout: ${expression}`); };
  if (await evaluate(`document.getElementById('login')!==null`)) await evaluate(`document.querySelector('[name=full_name]').value='Тестов Инженер Смены';document.getElementById('login').requestSubmit()`);
  await waitFor(`document.querySelector('.home-screen.active')!==null`);
  const clickText = text => evaluate(`(()=>{const active=document.querySelector('.view.active');const x=[...document.querySelectorAll('button')].find(x=>x.textContent.includes(${JSON.stringify(text)})&&!x.hidden&&(active?.contains(x)||x.closest('.top')||x.closest('.subnav')));if(!x)throw Error('active button: '+${JSON.stringify(text)});x.click();return true})()`);
  const assertClean = async label => { const value=await evaluate(`document.getElementById('interfaceError')?.textContent||''`); if(value)throw Error(`${label}: ${value}`); if(runtimeErrors.length) throw Error(`${label}: ${runtimeErrors.join('\\n')}`); if(resourceErrors.length) throw Error(`${label}: ${resourceErrors.join('\\n')}`); if(httpErrors.length) throw Error(`${label}: ${httpErrors.join('\\n')}`); };
  const assertHome = async label => { await waitFor(`document.querySelector('#home.active')!==null`); await assertClean(label); };
  await assertHome('home');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true}); await sleep(200);
  await evaluate(`(()=>{const visible=node=>node&&node.getBoundingClientRect().width>0&&node.getBoundingClientRect().height>0&&getComputedStyle(node).display!=='none';if(!visible(document.querySelector('.top-brand')))throw Error('mobile ODE home button hidden');if(!visible(document.querySelector('.profile-actions .shift-profile')))throw Error('mobile profile action hidden');if(!visible(document.getElementById('globalSearch')))throw Error('mobile global search hidden');if(document.documentElement.scrollWidth>innerWidth+2)throw Error('mobile page overflow: '+document.documentElement.scrollWidth+'/'+innerWidth);return true})()`);
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false}); await sleep(200);
  await evaluate(`(()=>{const now=new Date(),pad=value=>String(value).padStart(2,'0'),expected=[now.getFullYear(),pad(now.getMonth()+1),pad(now.getDate())].join('-');if(today!==expected)throw Error('today is not local date');if(!csvQuotedCell('=1+1').includes("'=1+1"))throw Error('CSV formula not neutralized');const button=choiceButton('<img src=x onerror=alert(1)>','',()=>{});if(button.querySelector('img')||!button.textContent.includes('<img'))throw Error('wizard choice label is not text-safe');return true})()`);
  await clickText('Склад'); await clickText('Принять оборудование'); await clickText('Сканировать оборудование');
  await clickText('К способам приемки');
  await waitFor(`document.querySelector('#receipt .scenario-stage').hidden&&!document.querySelector('#receipt .scenario-cards').hidden`);
  await clickText('Сканировать оборудование');
  for (const text of ['Оборудование','Сервер','Dell','PowerEdge R650']) await clickText(text);
  await evaluate(`if(wShelf.options.length<2)wShelf.add(new Option('A-01','A-01'));if(wDc.options.length<2)wDc.add(new Option('Ixcellerate','Ixcellerate'));wShelf.selectedIndex=1;wDc.selectedIndex=1;document.querySelector('.wizard-next').click()`);
  try { await waitFor(`document.getElementById('receiptScanner')&&!document.getElementById('receiptScanner').closest('.scanner-box').hidden&&document.getElementById('receipt').classList.contains('active')`); }
  catch (error) { throw new Error(error.message+' '+JSON.stringify(await evaluate(`({heading:document.querySelector('.wizard-shell h2')?.textContent,status:status?.textContent,uiError:interfaceError?.textContent,form:!!document.getElementById('scanReceiptForm'),scanner:!!document.getElementById('receiptScanner'),scannerHidden:document.getElementById('receiptScanner')?.closest('.scanner-box').hidden,receiptClass:document.getElementById('receipt')?.className,stageHidden:document.querySelector('#receipt .scenario-stage')?.hidden,stage:document.querySelector('#receipt .scenario-stage')?.innerText})`))); }
  for (const sn of ['ODE012-SMOKE-A','ODE012-SMOKE-B']) {
    await evaluate(`receiptScanner.value=${JSON.stringify(sn)};receiptScanner.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`); await sleep(250);
  }
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr').length===2&&document.getElementById('activeDrafts')&&!document.getElementById('activeDrafts').hidden`);
  await clickText('ODE'); await assertHome('ODE home'); visited.odeHome = true;
  await evaluate(`document.querySelector('#activeDrafts button').click()`);
  await waitFor(`document.getElementById('receipt').classList.contains('active')&&document.querySelectorAll('#scanReceiptBody tr').length===2`);
  await evaluate(`document.querySelector('#scanReceiptBody button').click()`);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr').length===1`);
  await evaluate(`document.getElementById('confirmScanReceipts').click()`); await sleep(500);
  await assertClean('receipt'); visited.receipt = true;
  await evaluate(`globalSearch.value='ODE012-SMOKE-B';globalSearch.dispatchEvent(new Event('input',{bubbles:true}))`);
  await waitFor(`document.querySelector('.global-search-result')?.textContent.includes('ODE012-SMOKE-B')`);
  await evaluate(`document.querySelector('.global-search-result').click()`);
  await waitFor(`document.getElementById('positionModal').classList.contains('show')&&document.getElementById('positionDetails').textContent.includes('ODE012-SMOKE-B')`);
  visited.globalSearch = true;
  await evaluate(`history.back()`);
  await waitFor(`!document.getElementById('positionModal').classList.contains('show')`);
  await evaluate(`location.reload()`); await sleep(600);
  await waitFor(`document.getElementById('receipt').classList.contains('active')&&document.getElementById('globalSearch')`);
  await assertClean('reload and browser back'); visited.reloadAndBack = true;
  await clickText('Расход'); await waitFor(`document.getElementById('issue').classList.contains('active')`); await assertClean('issue'); visited.issue = true;
  await clickText('Баланс'); await waitFor(`document.getElementById('balance').classList.contains('active')`); await assertClean('balance'); visited.balance = true;
  await waitFor(`document.querySelectorAll('#balanceKpis .kpi-card').length===6`);
  await evaluate(`(()=>{const card=[...document.querySelectorAll('#balanceKpis .kpi-card')].find(x=>x.textContent.includes('Серверы'));if(!card)throw Error('balance card: Серверы');card.click()})()`);
  await waitFor(`document.querySelector('#balanceKpis .kpi-card.active')?.textContent.includes('Серверы')`);
  await evaluate(`document.querySelector('#balanceKpis .reset-balance').click()`);
  await waitFor(`document.querySelector('#balanceKpis .kpi-card.active')===null`);
  await evaluate(`document.getElementById('balanceQuery').value='ODE012-SMOKE-B';document.getElementById('balanceQuery').dispatchEvent(new Event('input',{bubbles:true}))`);
  await waitFor(`document.querySelectorAll('#balanceBody tr').length>=1`);
  await evaluate(`(()=>{const button=[...document.querySelectorAll('#balanceBody button')].find(x=>x.textContent.includes('Открыть карточку'));if(!button)throw Error('position card button missing');button.click()})()`);
  await waitFor(`document.getElementById('positionModal').classList.contains('show')&&document.getElementById('positionDetails').textContent.includes('API')===false`);
  await evaluate(`closePositionCard()`);
  await evaluate(`document.getElementById('balanceQuery').value='';document.getElementById('balanceQuery').dispatchEvent(new Event('input',{bubbles:true}))`);
  await evaluate(`(()=>{const labels=[...document.querySelectorAll('#subnav .subtab')].map(x=>x.textContent.trim());if(!labels.includes('Проблемы')||!labels.includes('События'))throw Error('warehouse Problems/Events navigation missing');return true})()`);
  await clickText('Проблемы'); await waitFor(`currentSection==='warehouse'&&document.getElementById('problems').classList.contains('active')`); await assertClean('warehouse problems');
  await clickText('События'); await waitFor(`currentSection==='warehouse'&&document.getElementById('journal').classList.contains('active')`);
  await waitFor(`document.querySelector('#operationBody')&&document.querySelector('.history-summary')&&(document.querySelectorAll('#operationBody tr').length>0||document.querySelector('.history-empty'))`);
  await evaluate(`(()=>{const input=document.querySelector('#journal .history-search');if(!input)throw Error('history search missing');input.value='ODE012-SMOKE-B';input.dispatchEvent(new Event('input',{bubbles:true}))})()`);
  await waitFor(`document.querySelectorAll('#operationBody tr').length>0||document.querySelector('.history-empty')`);
  await evaluate(`(()=>{const reset=document.querySelector('#journal .history-reset');if(!reset)throw Error('history reset missing');reset.click()})()`);
  await waitFor(`document.querySelector('#journal .history-search').value===''`);
  await assertClean('history'); visited.history = true;
  await clickText('Профиль'); await waitFor(`document.getElementById('profile').classList.contains('active')&&document.getElementById('shiftProfileCard')&&!document.getElementById('shiftProfileCard').hidden`); await assertClean('profile'); visited.profile = true;
  await clickText('Обновить'); await sleep(300); await assertClean('refresh');
  await clickText('ODE'); await assertHome('ODE home after profile');
  await clickText('Отчеты'); await waitFor(`document.getElementById('daily').classList.contains('active')`);
  await evaluate(`(()=>{const f=document.getElementById('dailyForm'),today=new Date().toISOString().slice(0,10);f.elements.namedItem('date').value=today;f.requestSubmit()})()`);
  await waitFor(`document.querySelectorAll('#dailyBody tr').length>0`);
  await clickText('Логи работ'); await waitFor(`document.getElementById('worklogs').classList.contains('active')`);
  await evaluate(`(()=>{const f=document.getElementById('workLogForm');f.elements.namedItem('work_date').value=new Date().toISOString().slice(0,10);const source=f.elements.namedItem('task_source'),type=f.elements.namedItem('task_type'),status=f.elements.namedItem('status');if(source.options.length>1)source.selectedIndex=1;if(type.options.length>1)type.selectedIndex=1;f.elements.namedItem('task_number').value='SMOKE-WORKLOG-1';f.elements.namedItem('description').value='Проверка ReportsFacade read API';if(status.options.length>1)status.selectedIndex=1;f.elements.namedItem('comment').value='smoke';f.requestSubmit()})()`);
  await sleep(400);
  await evaluate(`document.getElementById('workLogFilter').requestSubmit()`);
  await waitFor(`document.getElementById('workLogBody').textContent.includes('SMOKE-WORKLOG-1')`);
  await waitFor(`document.getElementById('exportWorkLogs').href.includes('/export/work-logs.csv')`);
  await clickText('Еженедельный'); await waitFor(`document.getElementById('weekly').classList.contains('active')`);
  await evaluate(`(()=>{const f=document.getElementById('weeklyForm'),today=new Date().toISOString().slice(0,10);f.elements.namedItem('start_date').value=today;f.elements.namedItem('end_date').value=today;f.requestSubmit()})()`);
  await waitFor(`document.querySelectorAll('#weeklyCards .card').length>0&&document.getElementById('downloadWeekly').onclick`);
  await assertClean('reports'); visited.reports = true; await clickText('ODE'); await assertHome('ODE home after reports');
  await clickText('Мониторинг'); await waitFor(`document.getElementById('monitoring').classList.contains('active')`);
  await evaluate(`(()=>{const root=document.getElementById('monitoring'),buttons=[...root.querySelectorAll('button')].map(x=>x.textContent.trim());if(!/в разработке/i.test(root.textContent))throw Error('monitoring placeholder missing');if(buttons.some(x=>x.includes('Проблемы')||x.includes('События')))throw Error('warehouse actions leaked into Monitoring');return true})()`);
  await assertClean('monitoring'); await clickText('ODE'); await assertHome('ODE home after monitoring');
  await clickText('Профиль'); await waitFor(`document.getElementById('profile').classList.contains('active')`); await assertClean('profile card'); await clickText('ODE'); await assertHome('ODE home after profile card');
  await clickText('Склад'); visited.warehouse = true; await clickText('Поставки'); await assertClean('deliveries');
  await evaluate(`(()=>{const row=document.querySelector('#deliveryBody tr');const button=row&&[...row.querySelectorAll('button')].find(x=>x.textContent.includes('Открыть'));if(button)button.click();return true})()`);
  await assertClean('delivery optional card');
  await clickText('Инвентаризация'); await assertClean('inventory'); await clickText('ODE'); await assertHome('ODE home final');
  await clickText('Сменить инженера'); await waitFor(`document.getElementById('login')!==null`);
  await evaluate(`document.getElementById('mode').click();document.querySelector('[name=email]').value='lokolis';document.querySelector('[name=password]').value='lokolis';document.getElementById('login').requestSubmit()`);
  await waitFor(`document.querySelector('.home-screen.active')!==null`);
  await waitFor(`document.querySelector('[data-section="administration"]')&&!document.querySelector('[data-section="administration"]').hidden`);
  await evaluate(`document.querySelector('[data-section="administration"]').click()`);
  await waitFor(`document.getElementById('admin').classList.contains('active')`);
  await waitFor(`document.getElementById('userBody').textContent.includes('lokolis')`);
  await evaluate(`fetch('/api/admin').then(async response=>{if(!response.ok)throw Error('admin API '+response.status);const body=await response.json();if(!body.users?.some(user=>user.email==='lokolis'))throw Error('admin API user missing');return true})`);
  await assertClean('admin users');
  await clickText('Резервные копии');
  await waitFor(`document.getElementById('admin').classList.contains('active')&&(document.querySelectorAll('#backupBody tr').length>0||document.getElementById('backupBody').textContent.includes('Резервных копий нет'))`);
  await assertClean('admin backups');
  await clickText('Журнал действий');
  await waitFor(`document.getElementById('admin').classList.contains('active')&&(document.querySelectorAll('#auditBody tr').length>0||document.getElementById('auditBody').textContent.includes('Записей аудита нет'))`);
  await assertClean('admin audit');
  await clickText('Сменить пароль');
  await waitFor(`document.getElementById('profile').classList.contains('active')&&document.getElementById('passwordForm')&&!document.getElementById('passwordForm').closest('.box').hidden`);
  await assertClean('admin password profile');
  visited.administration = true;
  await clickText('ODE'); await assertHome('ODE home after admin');
  const result = await evaluate(`({home:document.querySelector('#home.active')!==null,errors:document.getElementById('interfaceError')?.textContent||'',receiptSaved:state.recent_receipts.some(x=>x.serial_number==='ODE012-SMOKE-B'),balanceCards:document.querySelectorAll('#balanceKpis .kpi-card').length})`);
  result.noConsoleErrors = runtimeErrors.length === 0;
  result.noWindowErrors = !result.errors;
  result.noUnhandledRejections = !result.errors && runtimeErrors.length === 0;
  result.noResourceErrors = resourceErrors.length === 0;
  result.noHttpErrors = httpErrors.length === 0;
  result.noApi500 = apiErrors.length === 0;
  result.visited = visited;
  console.log(JSON.stringify(result)); ws.close();
  if (!result.home || result.errors || !result.receiptSaved || result.balanceCards!==6 || !result.noConsoleErrors || !result.noResourceErrors || !result.noHttpErrors || !result.noApi500 || Object.values(visited).some(x=>!x)) process.exitCode = 1;
})().catch(e => { console.error(e); process.exit(1); });
