/* Run against Chrome --remote-debugging-port=9223 and a disposable ODE database. */
const http = require('http');
const get = url => new Promise((resolve, reject) => http.get(url, r => {
  let body = ''; r.on('data', c => body += c); r.on('end', () => resolve(JSON.parse(body)));
}).on('error', reject));
const sleep = ms => new Promise(r => setTimeout(r, ms));

(async () => {
  const appUrl=process.argv[2]||'http://127.0.0.1:8876',debugPort=process.argv[3]||'9223';
  const pages = await get(`http://127.0.0.1:${debugPort}/json`);
  const page = pages.find(x => x.type === 'page' && x.url.startsWith(appUrl));
  if (!page) throw new Error('ODE page not found');
  const ws = new WebSocket(page.webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
  let id = 0; const pending = new Map();
  const runtimeErrors = [];
  const resourceErrors = [];
  const apiErrors = [];
  const httpErrors = [];
  ws.onmessage = event => {
    const m = JSON.parse(event.data);
    if (m.method === 'Runtime.exceptionThrown') runtimeErrors.push(m.params.exceptionDetails.exception?.description || m.params.exceptionDetails.text);
    if (m.method === 'Log.entryAdded' && ['error', 'warning'].includes(m.params.entry.level)) runtimeErrors.push(m.params.entry.text);
    if (m.method === 'Network.loadingFailed') resourceErrors.push(`${m.params.type}: ${m.params.errorText}`);
    if (m.method === 'Network.responseReceived' && m.params.response.status >= 400) {
      httpErrors.push(`${m.params.response.status}: ${m.params.response.url}`);
      if (m.params.response.status >= 500) apiErrors.push(`${m.params.response.status}: ${m.params.response.url}`);
    }
    if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); }
  };
  const send = (method, params = {}) => new Promise((resolve,reject) => { const n = ++id,t=setTimeout(()=>{pending.delete(n);reject(Error(`CDP timeout: ${method}`))},5000);pending.set(n,m=>{clearTimeout(t);resolve(m)});ws.send(JSON.stringify({id:n, method, params})); });
  await send('Runtime.enable'); await send('Log.enable'); await send('Network.enable');
  const visited = {odeHome:false,warehouse:false,receipt:false,issue:false,balance:false,history:false,reports:false,knowledge:false,profile:false,administration:false,monitoring:false,globalSearch:false,reloadAndBack:false,inventoryNumbers:false};
  const smokeToken=Date.now().toString(36).toUpperCase();
  const serials={a:`ODE012-${smokeToken}-A`,b:`ODE012-${smokeToken}-B`,c:`ODE012-${smokeToken}-C`};
  const assignedInventory=`INV-ODE013-${smokeToken}`;
  const bulkAssignedInventory=`INV-BULK-ODE013-${smokeToken}`;
  const inventoryNumberCsv=`Serial Number,Inventory Number\r\n${serials.a},${bulkAssignedInventory}\r\n`;
  const receiptTemps=[`ODE012-${smokeToken}-CLEAR-1`,`ODE012-${smokeToken}-CLEAR-2`];
  const unknownIssue=`ODE012-${smokeToken}-UNKNOWN`;
  const pairSource=`ODE013-${smokeToken}-PAIR-TRANSCEIVER`;
  const evaluate = async expression => {
    const m = await send('Runtime.evaluate', {expression, awaitPromise:true, returnByValue:true});
    if (m.result?.exceptionDetails) throw new Error(m.result.exceptionDetails.exception?.description||m.result.exceptionDetails.text);
    return m.result?.result?.value;
  };
  const waitFor = async expression => { for (let i=0;i<50;i++) { if (await evaluate(expression)) return; await sleep(100); } throw new Error(`Timeout: ${expression}`); };
  const scanInto = async (inputId,serial) => { await evaluate(`(()=>{const input=document.getElementById(${JSON.stringify(inputId)});input.value=${JSON.stringify(serial)};input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));return true})()`); await sleep(220); };
  const uploadInventoryNumberCsv = () => evaluate(`(()=>{const input=document.getElementById('inventoryNumberCsv'),transfer=new DataTransfer(),file=new File([${JSON.stringify(inventoryNumberCsv)}],'inventory_numbers.csv',{type:'text/csv;charset=utf-8'});transfer.items.add(file);input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));return true})()`);
  const installAutoConfirm = () => evaluate(`window.__confirmCalls=0;window.confirm=()=>{window.__confirmCalls+=1;return true}`);
  await evaluate(`localStorage.setItem('ode_receipt_draft',JSON.stringify({rows:[{serial_number:'OLD-TEST-DRAFT'}],fields:{}}))`);
  if (await evaluate(`document.getElementById('login')!==null`)) await evaluate(`document.querySelector('[name=full_name]').value='Тестов Инженер Смены';document.getElementById('login').requestSubmit()`);
  await waitFor(`document.querySelector('.home-screen.active')!==null&&typeof state!=='undefined'&&state.current_user?.first_name`);
  await evaluate(`(()=>{if(!document.getElementById('currentUser').textContent.includes('Тестов Инженер Смены'))throw Error('selected engineer is missing in header');return true})()`);
  await waitFor(`!localStorage.getItem('ode_receipt_draft')&&!document.querySelector('#receipt .draft-choice')`);
  const clickText = text => evaluate(`(()=>{const active=document.querySelector('.view.active');const x=[...document.querySelectorAll('button')].find(x=>x.textContent.includes(${JSON.stringify(text)})&&!x.hidden&&x.getClientRects().length>0&&(active?.contains(x)||x.closest('.top')||x.closest('.subnav')));if(!x)throw Error('active button: '+${JSON.stringify(text)});x.click();return true})()`);
  const assertClean = async label => { const value=await evaluate(`document.getElementById('interfaceError')?.textContent||''`); if(value)throw Error(`${label}: ${value}`); if(runtimeErrors.length) throw Error(`${label}: ${runtimeErrors.join('\\n')}`); if(resourceErrors.length) throw Error(`${label}: ${resourceErrors.join('\\n')}`); if(httpErrors.length) throw Error(`${label}: ${httpErrors.join('\\n')}`); };
  const assertHome = async label => { await waitFor(`document.querySelector('#home.active')!==null`); await assertClean(label); };
  await assertHome('home');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true}); await sleep(200);
  await evaluate(`(()=>{const visible=node=>node&&node.getBoundingClientRect().width>0&&node.getBoundingClientRect().height>0&&getComputedStyle(node).display!=='none';if(!visible(document.querySelector('.top-brand')))throw Error('mobile ODE home button hidden');if(!visible(document.querySelector('.portal-grid .portal-card[data-module="profile"]')))throw Error('mobile profile card hidden');if(!visible(document.getElementById('globalSearchTrigger')))throw Error('mobile global search lupe hidden');if(document.documentElement.scrollWidth>innerWidth+2)throw Error('mobile page overflow: '+document.documentElement.scrollWidth+'/'+innerWidth);return true})()`);
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false}); await sleep(200);
  await evaluate(`(()=>{const now=new Date(),pad=value=>String(value).padStart(2,'0'),expected=[now.getFullYear(),pad(now.getMonth()+1),pad(now.getDate())].join('-');if(today!==expected)throw Error('today is not local date');if(!csvQuotedCell('=1+1').includes("'=1+1"))throw Error('CSV formula not neutralized');const button=choiceButton('<img src=x onerror=alert(1)>','',()=>{});if(button.querySelector('img')||!button.textContent.includes('<img'))throw Error('wizard choice label is not text-safe');return true})()`);
  await evaluate(`(()=>{const all=[...document.querySelectorAll('.portal-grid .portal-card')],cards=all.filter(card=>!card.hidden),modules=cards.map(card=>card.dataset.module),routes=cards.map(card=>card.dataset.route),adminEntry=document.querySelector('.admin-entry');if(cards.length!==5||modules.join(',')!=='warehouse,monitoring,knowledge,profile,reports')throw Error('engineer module cards contract: '+modules.join(','));if(routes.join(',')!=='warehouse/overview,monitoring/monitoring,knowledge/home,profile/profile,reports/worklogs')throw Error('module card routes: '+routes.join(','));if(!all.find(card=>card.dataset.module==='administration')?.hidden)throw Error('administration portal visible without backend permission');if(!adminEntry?.hidden||adminEntry.getClientRects().length)throw Error('administration header visible without backend permission');return true})()`);
  await evaluate(`document.querySelector('[data-module-open="monitoring"]').click()`);
  await waitFor(`document.getElementById('monitoring').classList.contains('active')&&location.hash==='#monitoring/monitoring'`);
  await evaluate(`(()=>{const root=document.getElementById('monitoring'),button=root.querySelector('.monitoring-tool-launcher');if(!root.textContent.includes('Инструменты мониторинга')||!button||!button.getClientRects().length)throw Error('monitoring launcher contract');return true})()`);
  visited.monitoring=true;await clickText('ODE');await assertHome('home after monitoring card');visited.odeHome=true;
  await installAutoConfirm();
  await evaluate(`document.querySelector('[data-module-open="warehouse"]').click()`);
  await waitFor(`document.getElementById('overview').classList.contains('active')&&document.querySelectorAll('#overview .warehouse-overview-stat').length>0&&location.hash==='#warehouse/overview'`);
  await evaluate(`(()=>{if(document.getElementById('balanceBody').children.length)throw Error('hidden balance table rendered eagerly');if(document.querySelectorAll('*').length>6000)throw Error('warehouse overview DOM unexpectedly large: '+document.querySelectorAll('*').length);return true})()`);
  visited.warehouse=true;await clickText('Приход'); await waitFor(`document.getElementById('receipt').classList.contains('active')`);
  await evaluate(`(()=>{if(!document.querySelector('#receipt > .task-hint')?.hidden)throw Error('legacy receipt hint visible before scenario selection');return true})()`);
  await clickText('Ручное добавление');
  await waitFor(`document.getElementById('stockReceiptForm').getClientRects().length>0`);
  await evaluate(`(()=>{const visibleForms=[...document.querySelectorAll('#receipt form')].filter(form=>form.getClientRects().length>0),supplier=document.querySelector('#simpleReceiptForm [name="supplier"]');if(visibleForms.length!==1||visibleForms[0].id!=='stockReceiptForm')throw Error('manual receipt scenario exposes unrelated forms: '+visibleForms.map(form=>form.id).join(','));if([...supplier.options].filter(item=>item.textContent==='Не указан').length!==1)throw Error('supplier placeholder duplicated');return true})()`);
  await clickText('Назад к способам прихода'); await clickText('Сканировать оборудование');
  await clickText('К способам приемки');
  await waitFor(`document.querySelector('#receipt .scenario-stage').hidden&&!document.querySelector('#receipt .scenario-cards').hidden`);
  await clickText('Сканировать оборудование');
  await evaluate(`(()=>{const button=[...document.querySelectorAll('#receipt .wizard-choice')].find(item=>item.querySelector('strong')?.textContent==='Оборудование'&&item.getClientRects().length>0);if(!button)throw Error('equipment category choice');button.click();return true})()`);
  await evaluate(`(()=>{const choices=[...document.querySelectorAll('#receipt .wizard-choice')].filter(item=>item.getClientRects().length>0),button=choices.find(item=>/сервер|server/i.test(item.textContent));if(!button)throw Error('server type choice: '+document.querySelector('#receipt .wizard-shell h2')?.textContent+' / '+choices.map(item=>item.textContent).join(', '));button.click();return true})()`);
  for (const text of ['Dell','PowerEdge R650']) await clickText(text);
  await evaluate(`if(wShelf.options.length<2)wShelf.add(new Option('A-01','A-01'));if(wDc.options.length<2)wDc.add(new Option('Ixcellerate','Ixcellerate'));wShelf.selectedIndex=1;wDc.selectedIndex=1;document.querySelector('.wizard-next').click()`);
  try { await waitFor(`document.getElementById('receiptScanner')&&!document.getElementById('receiptScanner').closest('.scanner-box').hidden&&document.getElementById('receipt').classList.contains('active')`); }
  catch (error) { throw new Error(error.message+' '+JSON.stringify(await evaluate(`({heading:document.querySelector('.wizard-shell h2')?.textContent,status:status?.textContent,uiError:interfaceError?.textContent,form:!!document.getElementById('scanReceiptForm'),scanner:!!document.getElementById('receiptScanner'),scannerHidden:document.getElementById('receiptScanner')?.closest('.scanner-box').hidden,receiptClass:document.getElementById('receipt')?.className,stageHidden:document.querySelector('#receipt .scenario-stage')?.hidden,stage:document.querySelector('#receipt .scenario-stage')?.innerText})`))); }
  for (const serial of Object.values(serials)) await scanInto('receiptScanner',serial);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===3&&JSON.parse(localStorage.getItem(scanDraftStorageKey('receipt'))).scanned_rows.length===3&&document.getElementById('scanReceiptCount').textContent.startsWith('3 ')`);
  await scanInto('receiptScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===3&&document.getElementById('status').textContent==='Этот S/N уже находится в текущем списке'&&document.querySelector('#scanReceiptBody tr.scan-duplicate')&&document.activeElement===document.getElementById('receiptScanner')`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('.scanner-delete').click();return true})()`);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem(scanDraftStorageKey('receipt'))).scanned_rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})&&document.activeElement===document.getElementById('receiptScanner')&&window.__confirmCalls===0`);
  await scanInto('receiptScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===3`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('input[type=checkbox]').click();document.getElementById('deleteSelectedReceipts').click();return true})()`);
  await waitFor(`window.__confirmCalls===1&&document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem(scanDraftStorageKey('receipt'))).scanned_rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})`);
  await evaluate(`(()=>{const key=scanDraftStorageKey('receipt'),draft=JSON.parse(localStorage.getItem(key));draft.scanned_rows.push({...draft.scanned_rows[0],serial_number:draft.scanned_rows[0].serial_number.toLowerCase()});localStorage.setItem(key,JSON.stringify(draft));location.reload()})()`);await sleep(750);
  await waitFor(`document.getElementById('receipt').classList.contains('active')&&document.querySelector('#receipt .draft-choice')&&typeof state!=='undefined'&&state.current_user?.first_name`);
  await evaluate(`(()=>{if(currentUserDisplayName()!=='Тестов Инженер Смены')throw Error('engineer changed after reload');return true})()`);
  await installAutoConfirm();
  await evaluate(`([...document.querySelectorAll('#receipt .draft-choice button')].find(button=>button.textContent.includes('Продолжить черновик'))).click()`);
  await waitFor(`document.getElementById('receipt').classList.contains('active')&&document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2&&JSON.parse(localStorage.getItem(scanDraftStorageKey('receipt'))).scanned_rows.length===2&&document.activeElement===document.getElementById('receiptScanner')`);
  visited.reloadAndBack=true;
  await evaluate(`document.getElementById('confirmScanReceipts').click()`);
  try{await waitFor(`!localStorage.getItem(scanDraftStorageKey('receipt'))&&state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.a)})&&state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.c)})&&!state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.b)})`)}catch(error){throw new Error(error.message+' '+JSON.stringify(await evaluate(`({status:document.getElementById('status')?.textContent,draft:readScanDraft('receipt'),rows:scanDraftRows('receipt'),fields:formData(document.getElementById('scanReceiptForm')),confirming:scanDraftRuntime.receipt.confirming})`)))};
  for(const serial of receiptTemps)await scanInto('receiptScanner',serial);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2`);
  await evaluate(`document.getElementById('clearScannedReceipts').click()`);
  await waitFor(`window.__confirmCalls===1&&!localStorage.getItem(scanDraftStorageKey('receipt'))&&document.querySelector('#scanReceiptBody .scanner-empty')&&document.activeElement===document.getElementById('receiptScanner')`);
  await scanInto('receiptScanner',serials.b);await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===1`);
  await evaluate(`document.getElementById('confirmScanReceipts').click()`);
  await waitFor(`!localStorage.getItem(scanDraftStorageKey('receipt'))&&state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.b)})`);
  await evaluate(`actionJson({action:'STOCK_RECEIPT',receipt_date:today,responsible:'Тестовый Инженер',supplier:'Не указан',item_name:'Трансивер XFUSION xFusion OMXD300201',project:'',serial_number:${JSON.stringify(pairSource)},inventory_number:'',vendor:'xFusion',model:'xFusion OMXD300201',shelf:'A-01',object_name:'Склад Ixcellerate',datacenter:'Ixcellerate',equipment_type:'',component_type:'Трансивер',cable_type:'',unit:'шт',quantity:1})`);
  await waitFor(`fetch('/api/position-search?'+new URLSearchParams({query:${JSON.stringify(pairSource)}})).then(response=>response.json()).then(result=>Number(result.rows[0]?.balance)===1)`);
  await assertClean('receipt draft deletion');visited.receipt=true;
  await evaluate(`document.getElementById('globalSearchTrigger').click()`);
  await waitFor(`document.getElementById('globalSearchModal').classList.contains('show')&&document.activeElement===document.getElementById('globalSearch')`);
  await evaluate(`globalSearch.value='stale query';globalSearch.dispatchEvent(new Event('input',{bubbles:true}));globalSearch.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  await waitFor(`!document.getElementById('globalSearchModal').classList.contains('show')&&document.activeElement===document.getElementById('globalSearchTrigger')&&!document.getElementById('globalSearchResults').children.length`);
  await evaluate(`document.getElementById('globalSearchTrigger').click();globalSearch.value=${JSON.stringify(serials.b)};globalSearch.dispatchEvent(new Event('input',{bubbles:true}))`);
  await waitFor(`document.querySelector('.global-search-result')?.textContent.includes(${JSON.stringify(serials.b)})`);
  await evaluate(`document.querySelector('.global-search-result').click()`);
  await waitFor(`document.getElementById('positionModal').classList.contains('show')&&document.getElementById('positionDetails').textContent.includes(${JSON.stringify(serials.b)})`);
  await waitFor(`document.querySelector('#positionDetails .equipment-inventory-assignment input[name="inventory_number"]')!==null`);
  await evaluate(`(()=>{const form=document.querySelector('#positionDetails .equipment-inventory-assignment');form.elements.namedItem('inventory_number').value=${JSON.stringify(assignedInventory)};form.requestSubmit();return true})()`);
  await waitFor(`document.getElementById('positionDetails').textContent.includes(${JSON.stringify(assignedInventory)})&&!document.querySelector('#positionDetails .equipment-inventory-assignment')&&document.getElementById('positionHistory').textContent.includes('EQUIPMENT_INVENTORY_NUMBER_ASSIGNED')`);
  await assertClean('equipment inventory number assignment');
  visited.globalSearch = true;
  await evaluate(`history.back()`);
  await waitFor(`!document.getElementById('positionModal').classList.contains('show')`);
  await clickText('Расход');await waitFor(`document.getElementById('issue').classList.contains('active')`);
  await evaluate(`(()=>{const root=document.getElementById('issue'),visibleDirect=[...root.children].filter(node=>node.getClientRects().length>0);if(!root.querySelector(':scope > .task-hint')?.hidden)throw Error('legacy issue hint visible before scenario selection');if(visibleDirect.some(node=>node.matches('.import-box,h2,.hint')))throw Error('unselected issue form content visible');if(![...root.querySelectorAll('.scenario-card')].some(button=>button.textContent.includes('Импорт расхода')))throw Error('issue import scenario missing');return true})()`);
  await clickText('Списать сканером');
  await waitFor(`document.getElementById('issueScanner')&&!document.getElementById('issueScanner').closest('.scanner-box').hidden`);
  await installAutoConfirm();
  await evaluate(`(()=>{const form=document.getElementById('scanIssueForm'),task=form.elements.namedItem('task_type');if(![...task.options].some(option=>option.value==='ПНР'))task.add(new Option('ПНР','ПНР'));task.value='ПНР';form.elements.namedItem('task_number').value='SMOKE-'+${JSON.stringify(smokeToken)};return true})()`);
  await clickText('Пары: компонент → оборудование');
  await waitFor(`issueScanMode==='pairs'&&document.getElementById('issuePairPrompt').dataset.step==='source'`);
  await scanInto('issueScanner',pairSource);
  await waitFor(`pendingIssueSource?.serial_number===${JSON.stringify(pairSource)}&&document.getElementById('issuePairPrompt').dataset.step==='target'`);
  await scanInto('issueScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===1&&scanDraftRows('issue')[0]?.target_serial_number===${JSON.stringify(serials.b)}`);
  await evaluate(`document.getElementById('confirmScanIssues').click()`);
  await waitFor(`!scanDraftRuntime.issue.confirming&&!scanDraftRows('issue').length&&fetch('/api/position-search?'+new URLSearchParams({query:${JSON.stringify(pairSource)}})).then(response=>response.json()).then(result=>Number(result.rows[0]?.balance)===0)`);
  await clickText('На одно оборудование');
  await waitFor(`issueScanMode==='fixed'`);
  for(const serial of Object.values(serials))await scanInto('issueScanner',serial);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===3&&JSON.parse(localStorage.getItem(scanDraftStorageKey('issue'))).scanned_rows.length===3`);
  await scanInto('issueScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===3&&document.getElementById('status').textContent==='Этот S/N уже находится в текущем списке'&&document.querySelector('#scanIssueBody tr.scan-duplicate')`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanIssueBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('.scanner-delete').click();return true})()`);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem(scanDraftStorageKey('issue'))).scanned_rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})&&window.__confirmCalls===0&&document.activeElement===document.getElementById('issueScanner')`);
  await scanInto('issueScanner',serials.b);await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===3`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanIssueBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('input[type=checkbox]').click();document.getElementById('deleteSelectedIssues').click();return true})()`);
  await waitFor(`window.__confirmCalls===1&&document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem(scanDraftStorageKey('issue'))).scanned_rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})`);
  await evaluate(`location.reload()`);await sleep(750);await waitFor(`document.getElementById('issue')?.classList.contains('active')&&document.querySelector('#issue .draft-choice')&&typeof state!=='undefined'&&state.current_user?.first_name`);await evaluate(`(()=>{if(currentUserDisplayName()!=='Тестов Инженер Смены')throw Error('engineer changed after issue reload');return true})()`);await installAutoConfirm();
  await evaluate(`([...document.querySelectorAll('#issue .draft-choice button')].find(button=>button.textContent.includes('Продолжить черновик'))).click()`);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===2&&JSON.parse(localStorage.getItem(scanDraftStorageKey('issue'))).scanned_rows.length===2&&document.activeElement===document.getElementById('issueScanner')`);
  await evaluate(`document.getElementById('confirmScanIssues').click()`);
  await waitFor(`!localStorage.getItem(scanDraftStorageKey('issue'))&&!scanDraftRuntime.issue.confirming`);
  const verifiedIssueBalances=await evaluate(`Promise.all(${JSON.stringify(Object.values(serials))}.map(serial=>fetch('/api/position-search?'+new URLSearchParams({query:serial})).then(response=>response.json()))).then(results=>{const balances=results.map(result=>Number(result.rows[0]?.balance));if(balances[0]!==0||balances[1]!==1||balances[2]!==0)throw Error('issue draft balances '+balances.join(','));return balances})`);
  await scanInto('issueScanner',serials.b);await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===1`);await scanInto('issueScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===1&&document.getElementById('status').textContent==='Этот S/N уже находится в текущем списке'`);
  await scanInto('issueScanner',unknownIssue);await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===1&&document.getElementById('status').textContent==='S/N не найден — расход запрещён'`);
  await evaluate(`loadAll()`);await waitFor(`!state.problems.unmatched_issues.some(row=>row.serial_number===${JSON.stringify(unknownIssue)})`);
  await evaluate(`document.getElementById('clearScannedIssues').click()`);
  await waitFor(`window.__confirmCalls===1&&!localStorage.getItem(scanDraftStorageKey('issue'))&&document.querySelector('#scanIssueBody .scanner-empty')&&document.activeElement===document.getElementById('issueScanner')`);
  await assertClean('issue draft deletion');visited.issue=true;
  await clickText('Остатки'); await waitFor(`document.getElementById('balance').classList.contains('active')`); await assertClean('balance'); visited.balance = true;
  await waitFor(`document.querySelectorAll('#balanceSummary .warehouse-summary-card').length===4&&!document.getElementById('balanceKpis')`);
  await waitFor(`document.getElementById('uxBalanceStock').value==='positive'&&document.querySelectorAll('#balanceBody tr').length<=500&&document.querySelectorAll('#balance .balance-filter-field').length===8`);
  await evaluate(`document.getElementById('uxBalanceStock').value='';document.getElementById('uxBalanceStock').dispatchEvent(new Event('change',{bubbles:true}))`);
  await waitFor(`document.getElementById('uxBalanceStock').value===''`);
  await evaluate(`document.getElementById('balanceQuery').value=${JSON.stringify(serials.a)};document.getElementById('balanceQuery').dispatchEvent(new Event('input',{bubbles:true}))`);
  await waitFor(`(()=>{const row=[...document.querySelectorAll('#balanceBody tr')].find(item=>item.textContent.includes(${JSON.stringify(serials.a)})),button=row&&[...row.querySelectorAll('button')].find(item=>item.textContent.includes('Списать'));return button?.disabled===true})()`);
  await evaluate(`document.getElementById('balanceQuery').value=${JSON.stringify(serials.b)};document.getElementById('balanceQuery').dispatchEvent(new Event('input',{bubbles:true}))`);
  await waitFor(`(()=>{const row=[...document.querySelectorAll('#balanceBody tr')].find(item=>item.textContent.includes(${JSON.stringify(serials.b)})),button=row&&[...row.querySelectorAll('button')].find(item=>item.textContent.includes('Списать'));return button?.disabled===false})()`);
  await evaluate(`(()=>{const row=[...document.querySelectorAll('#balanceBody tr')].find(item=>item.textContent.includes(${JSON.stringify(serials.b)})),button=row&&[...row.querySelectorAll('button')].find(x=>x.textContent.includes('Открыть карточку'));if(!button)throw Error('position card button missing for expected S/N');button.click()})()`);
  await waitFor(`document.getElementById('positionModal').classList.contains('show')&&document.getElementById('positionDetails').textContent.includes(${JSON.stringify(serials.b)})`);
  await evaluate(`closePositionCard()`);
  await evaluate(`document.getElementById('balanceQuery').value='';document.getElementById('balanceQuery').dispatchEvent(new Event('input',{bubbles:true}))`);
  await evaluate(`(()=>{const labels=[...document.querySelectorAll('#subnav .subtab')].map(x=>x.textContent.trim());if(labels.includes('Проблемы')||labels.includes('События'))throw Error('legacy warehouse technical navigation leaked');return true})()`);
  await waitFor(`fetch('/api/position-card?'+new URLSearchParams({serial_number:${JSON.stringify(serials.a)}})).then(async response=>{if(!response.ok)return false;const card=await response.json(),types=(card.history||[]).map(row=>row.event_type);return types.includes('Приход')&&types.includes('Расход')})`);
  await clickText('Все события');
  await waitFor(`document.getElementById('journal').classList.contains('active')&&document.getElementById('operationBody').textContent.includes(${JSON.stringify(serials.a)})`);
  await evaluate(`(()=>{const rows=state.warehouse_history||[],actions=new Set(rows.filter(row=>${JSON.stringify(Object.values(serials))}.includes(row.serial_number)).map(row=>row.action));if(!actions.has('Приход')||!actions.has('Расход'))throw Error('warehouse event types missing: '+[...actions].join(','));for(let i=1;i<rows.length;i++){const previous=Date.parse(rows[i-1].event_date)||0,current=Date.parse(rows[i].event_date)||0;if(previous<current)throw Error('warehouse history order');}return true})()`);
  await assertClean('warehouse all events');
  await assertClean('equipment receipt and issue history'); visited.history = true;
  await evaluate(`document.querySelector('[data-module-open="profile"]').click()`); await waitFor(`document.getElementById('profile').classList.contains('active')&&document.getElementById('shiftProfileCard')&&!document.getElementById('shiftProfileCard').hidden`); await assertClean('profile'); visited.profile = true;
  await clickText('Обновить'); await sleep(300); await assertClean('refresh');
  await clickText('ODE'); await assertHome('ODE home after profile');
  await evaluate(`document.querySelector('[data-module-open="reports"]').click()`); await waitFor(`document.getElementById('worklogs').classList.contains('active')&&location.hash==='#reports/worklogs'`);
  await evaluate(`(()=>{const f=document.getElementById('workLogForm');window.__smokeWorkDate=f.elements.namedItem('work_date').value;if(!window.__smokeWorkDate)throw Error('work log date missing');const type=f.elements.namedItem('task_type'),status=f.elements.namedItem('status'),section=f.elements.namedItem('section'),source=document.querySelector('#uvrTaskTemplates option')?.value;if(type.options.length>1)type.selectedIndex=1;if(status.options.length>1)status.selectedIndex=1;if(section.options.length>1)section.selectedIndex=1;if(!source)throw Error('task source references missing');f.elements.namedItem('task_name').value=source+'-SMOKE-WORKLOG-1';f.elements.namedItem('description').value='Проверка ReportsFacade read API';f.elements.namedItem('comment').value='smoke';f.requestSubmit()})()`);
  await sleep(400);
  await waitFor(`document.getElementById('workLogBody').textContent.includes('SMOKE-WORKLOG-1')`);
  await waitFor(`document.getElementById('exportWorkLogs').href.includes('/export/work-logs.csv')`);
  await clickText('Отчет за смену'); await waitFor(`document.getElementById('daily').classList.contains('active')&&location.hash==='#reports/daily'`);
  await evaluate(`(()=>{const f=document.getElementById('shiftForm');f.elements.namedItem('date').value=window.__smokeWorkDate;f.requestSubmit()})()`); await waitFor(`document.getElementById('shiftBody').textContent.includes('SMOKE-WORKLOG-1')`);
  await assertClean('reports'); visited.reports = true; await clickText('ODE'); await assertHome('ODE home after reports');
  await evaluate(`document.querySelector('[data-module-open="knowledge"]').click()`); await waitFor(`document.getElementById('knowledge').classList.contains('active')&&location.hash.startsWith('#knowledge/')`);
  await waitFor(`document.getElementById('knowledge').textContent.includes('База знаний')`); await assertClean('knowledge'); visited.knowledge = true; await clickText('ODE'); await assertHome('ODE home after knowledge');
  await evaluate(`document.querySelector('[data-module-open="profile"]').click()`); await waitFor(`document.getElementById('profile').classList.contains('active')`); await assertClean('profile card'); await clickText('ODE'); await assertHome('ODE home after profile card');
  await evaluate(`document.querySelector('[data-module-open="warehouse"]').click()`);await waitFor(`document.getElementById('overview').classList.contains('active')`);await clickText('Поставки'); await assertClean('deliveries');
  await evaluate(`(()=>{const row=document.querySelector('#deliveryBody tr');const button=row&&[...row.querySelectorAll('button')].find(x=>x.textContent.includes('Открыть'));if(button)button.click();return true})()`);
  await assertClean('delivery optional card');
  await clickText('Инвентаризация'); await assertClean('inventory');
  await uploadInventoryNumberCsv();
  await waitFor(`document.getElementById('inventoryNumberImport')?.dataset.phase==='preview'&&document.querySelector('#inventoryNumberImport .inventory-number-status-success')?.textContent==='SUCCESS'&&!document.querySelector('#inventoryNumberImport .inventory-number-confirm')?.disabled`);
  await evaluate(`document.querySelector('#inventoryNumberImport .inventory-number-confirm').click()`);
  await waitFor(`document.getElementById('inventoryNumberImport')?.dataset.phase==='result'&&document.querySelector('#inventoryNumberImport .inventory-number-status-success')?.textContent==='SUCCESS'&&document.getElementById('inventoryNumberImport').textContent.includes(${JSON.stringify(bulkAssignedInventory)})`);
  await waitFor(`fetch('/api/position-card?'+new URLSearchParams({serial_number:${JSON.stringify(serials.a)}})).then(async response=>{if(!response.ok)return false;const card=await response.json();return card.position?.inventory_number===${JSON.stringify(bulkAssignedInventory)}&&card.history?.some(row=>String(row.event_type||'').includes('EQUIPMENT_INVENTORY_NUMBER_ASSIGNED'))})`);
  await uploadInventoryNumberCsv();
  await waitFor(`document.getElementById('inventoryNumberImport')?.dataset.phase==='preview'&&document.querySelector('#inventoryNumberImport .inventory-number-status-unchanged')?.textContent==='UNCHANGED'&&document.getElementById('inventoryNumberImport').textContent.includes(${JSON.stringify(bulkAssignedInventory)})`);
  await assertClean('inventory number CSV import');visited.inventoryNumbers=true;
  await clickText('ODE'); await assertHome('ODE home final');
  await clickText('Сменить инженера'); await waitFor(`document.getElementById('login')!==null`);
  await evaluate(`document.querySelector('[name=full_name]').value='Петров Пётр Петрович';document.getElementById('login').requestSubmit(document.querySelector('[data-mode=engineer]'))`);
  await waitFor(`document.querySelector('.home-screen.active')!==null&&currentUserDisplayName()==='Петров Пётр Петрович'&&document.getElementById('currentUser').textContent.includes('Петров Пётр Петрович')`);
  await evaluate(`location.reload()`);await sleep(750);
  await waitFor(`document.querySelector('.home-screen.active')!==null&&currentUserDisplayName()==='Петров Пётр Петрович'`);
  await clickText('Сменить инженера'); await waitFor(`document.getElementById('login')!==null`);
  await evaluate(`document.querySelector('[name=email]').value='lokolis';document.querySelector('[name=password]').value='lokolis';document.getElementById('login').requestSubmit(document.querySelector('[data-mode=admin]'))`);
  await waitFor(`document.querySelector('.home-screen.active')!==null&&typeof state!=='undefined'&&state.current_user?.role==='admin'`);
  await waitFor(`document.querySelector('.admin-access')&&!document.querySelector('.admin-access').hidden&&document.querySelector('.admin-access').getClientRects().length>0`);
  await evaluate(`document.querySelector('.admin-access').click()`);
  await waitFor(`document.getElementById('admin').classList.contains('active')`);
  await waitFor(`document.getElementById('userBody').textContent.includes('lokolis')`);
  await evaluate(`fetch('/api/admin').then(async response=>{if(!response.ok)throw Error('admin API '+response.status);const body=await response.json();if(!body.users?.some(user=>user.email==='lokolis'))throw Error('admin API user missing');return true})`);
  await assertClean('admin users');
  await clickText('Резервные копии');
  await waitFor(`document.getElementById('admin').classList.contains('active')&&(document.querySelectorAll('#backupBody tr').length>0||document.getElementById('backupBody').textContent.includes('Резервных копий нет'))`);
  await assertClean('admin backups');
  await clickText('Журнал действий');
  await waitFor(`document.getElementById('admin').classList.contains('active')&&(document.querySelectorAll('#auditBody tr').length>0||document.getElementById('auditBody').textContent.includes('Записей аудита нет'))`);
  await assertClean('admin audit');
  await clickText('Управление справочниками');
  await waitFor(`document.getElementById('references').classList.contains('active')&&document.getElementById('referenceEditorBody')&&document.getElementById('referenceEditorBody').children.length>0`);
  await evaluate(`fetch('/api/admin?section=references').then(async response=>{if(!response.ok)throw Error('reference editor API '+response.status);const body=await response.json(),dc=body.values.filter(value=>value.domain_key==='datacenter'&&value.active&&value.approval_status==='APPROVED');if(dc.length!==1||dc[0].display_name!=='Ixcellerate')throw Error('active datacenter editor contract');return true})`);
  await assertClean('reference editor');
  await clickText('ODE'); await assertHome('ODE home before admin password profile');
  await evaluate(`document.querySelector('[data-module-open="profile"]').click()`);
  await waitFor(`document.getElementById('profile').classList.contains('active')&&document.getElementById('passwordForm')&&!document.getElementById('passwordForm').closest('.box').hidden`);
  await assertClean('admin password profile');
  visited.administration = true;
  await clickText('ODE'); await assertHome('ODE home after admin');
  const result = await evaluate(`({home:document.querySelector('#home.active')!==null,errors:document.getElementById('interfaceError')?.textContent||'',receiptSaved:${JSON.stringify(Object.values(serials))}.every(serial=>state.recent_receipts.some(row=>row.serial_number===serial)),draftsCleared:!localStorage.getItem(scanDraftStorageKey('receipt'))&&!localStorage.getItem(scanDraftStorageKey('issue')),legacyDraftCleared:!localStorage.getItem('ode_receipt_draft'),adminVisible:!document.querySelector('.admin-access').hidden,summaryCards:document.querySelectorAll('#balanceSummary .warehouse-summary-card').length})`);
  result.issueBalances = verifiedIssueBalances;
  result.noConsoleErrors = runtimeErrors.length === 0;
  result.noWindowErrors = !result.errors;
  result.noUnhandledRejections = !result.errors && runtimeErrors.length === 0;
  result.noResourceErrors = resourceErrors.length === 0;
  result.noHttpErrors = httpErrors.length === 0;
  result.noApi500 = apiErrors.length === 0;
  result.visited = visited;
  console.log(JSON.stringify(result)); ws.close();
  if (!result.home || result.errors || !result.receiptSaved || result.issueBalances.join(',')!=='0,1,0' || !result.draftsCleared || !result.legacyDraftCleared || !result.adminVisible || result.summaryCards!==4 || !result.noConsoleErrors || !result.noResourceErrors || !result.noHttpErrors || !result.noApi500 || Object.values(visited).some(x=>!x)) process.exitCode = 1;
})().catch(e => { console.error(e); process.exit(1); });
