/* Run against Chrome --remote-debugging-port=9223 and a disposable ODE database. */
const http = require('http');
const get = url => new Promise((resolve, reject) => http.get(url, r => {
  let body = ''; r.on('data', c => body += c); r.on('end', () => resolve(JSON.parse(body)));
}).on('error', reject));
const sleep = ms => new Promise(r => setTimeout(r, ms));

(async () => {
  const appUrl=process.argv[2]||'http://127.0.0.1:8876',debugPort=process.argv[3]||'9223';
  const pages = await get(`http://127.0.0.1:${debugPort}/json`);
  const page = pages.find(x => x.type === 'page' && x.url.startsWith(appUrl));
  if (!page) throw new Error('ODE page not found');
  const ws = new WebSocket(page.webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
  let id = 0; const pending = new Map();
  const runtimeErrors = [];
  const resourceErrors = [];
  const apiErrors = [];
  const httpErrors = [];
  ws.onmessage = event => {
    const m = JSON.parse(event.data);
    if (m.method === 'Runtime.exceptionThrown') runtimeErrors.push(m.params.exceptionDetails.exception?.description || m.params.exceptionDetails.text);
    if (m.method === 'Log.entryAdded' && ['error', 'warning'].includes(m.params.entry.level)) runtimeErrors.push(m.params.entry.text);
    if (m.method === 'Network.loadingFailed') resourceErrors.push(`${m.params.type}: ${m.params.errorText}`);
    if (m.method === 'Network.responseReceived' && m.params.response.status >= 400) {
      httpErrors.push(`${m.params.response.status}: ${m.params.response.url}`);
      if (m.params.response.status >= 500) apiErrors.push(`${m.params.response.status}: ${m.params.response.url}`);
    }
    if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); }
  };
  const send = (method, params = {}) => new Promise((resolve,reject) => { const n = ++id,t=setTimeout(()=>{pending.delete(n);reject(Error(`CDP timeout: ${method}`))},5000);pending.set(n,m=>{clearTimeout(t);resolve(m)});ws.send(JSON.stringify({id:n, method, params})); });
  await send('Runtime.enable'); await send('Log.enable'); await send('Network.enable');
  const visited = {odeHome:false,warehouse:false,receipt:false,issue:false,balance:false,history:false,reports:false,profile:false,administration:false,monitoring:false,globalSearch:false,reloadAndBack:false};
  const smokeToken=Date.now().toString(36).toUpperCase();
  const serials={a:`ODE012-${smokeToken}-A`,b:`ODE012-${smokeToken}-B`,c:`ODE012-${smokeToken}-C`};
  const assignedInventory=`INV-ODE013-${smokeToken}`;
  const receiptTemps=[`ODE012-${smokeToken}-CLEAR-1`,`ODE012-${smokeToken}-CLEAR-2`];
  const unknownIssue=`ODE012-${smokeToken}-UNKNOWN`;
  const evaluate = async expression => {
    const m = await send('Runtime.evaluate', {expression, awaitPromise:true, returnByValue:true});
    if (m.result?.exceptionDetails) throw new Error(m.result.exceptionDetails.exception?.description||m.result.exceptionDetails.text);
    return m.result?.result?.value;
  };
  const waitFor = async expression => { for (let i=0;i<50;i++) { if (await evaluate(expression)) return; await sleep(100); } throw new Error(`Timeout: ${expression}`); };
  const scanInto = async (inputId,serial) => { await evaluate(`(()=>{const input=document.getElementById(${JSON.stringify(inputId)});input.value=${JSON.stringify(serial)};input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));return true})()`); await sleep(220); };
  const installAutoConfirm = () => evaluate(`window.__confirmCalls=0;window.confirm=()=>{window.__confirmCalls+=1;return true}`);
  if (await evaluate(`document.getElementById('login')!==null`)) await evaluate(`document.querySelector('[name=full_name]').value='Тестов Инженер Смены';document.getElementById('login').requestSubmit()`);
  await waitFor(`document.querySelector('.home-screen.active')!==null&&typeof state!=='undefined'&&state.current_user?.first_name`);
  const clickText = text => evaluate(`(()=>{const active=document.querySelector('.view.active');const x=[...document.querySelectorAll('button')].find(x=>x.textContent.includes(${JSON.stringify(text)})&&!x.hidden&&(active?.contains(x)||x.closest('.top')||x.closest('.subnav')));if(!x)throw Error('active button: '+${JSON.stringify(text)});x.click();return true})()`);
  const assertClean = async label => { const value=await evaluate(`document.getElementById('interfaceError')?.textContent||''`); if(value)throw Error(`${label}: ${value}`); if(runtimeErrors.length) throw Error(`${label}: ${runtimeErrors.join('\\n')}`); if(resourceErrors.length) throw Error(`${label}: ${resourceErrors.join('\\n')}`); if(httpErrors.length) throw Error(`${label}: ${httpErrors.join('\\n')}`); };
  const assertHome = async label => { await waitFor(`document.querySelector('#home.active')!==null`); await assertClean(label); };
  await assertHome('home');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true}); await sleep(200);
  await evaluate(`(()=>{const visible=node=>node&&node.getBoundingClientRect().width>0&&node.getBoundingClientRect().height>0&&getComputedStyle(node).display!=='none';if(!visible(document.querySelector('.top-brand')))throw Error('mobile ODE home button hidden');if(!visible(document.querySelector('.profile-actions .shift-profile')))throw Error('mobile profile action hidden');if(!visible(document.getElementById('globalSearchTrigger')))throw Error('mobile global search lupe hidden');if(document.documentElement.scrollWidth>innerWidth+2)throw Error('mobile page overflow: '+document.documentElement.scrollWidth+'/'+innerWidth);return true})()`);
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false}); await sleep(200);
  await evaluate(`(()=>{const now=new Date(),pad=value=>String(value).padStart(2,'0'),expected=[now.getFullYear(),pad(now.getMonth()+1),pad(now.getDate())].join('-');if(today!==expected)throw Error('today is not local date');if(!csvQuotedCell('=1+1').includes("'=1+1"))throw Error('CSV formula not neutralized');const button=choiceButton('<img src=x onerror=alert(1)>','',()=>{});if(button.querySelector('img')||!button.textContent.includes('<img'))throw Error('wizard choice label is not text-safe');return true})()`);
  await evaluate(`(()=>{const cards=[...document.querySelectorAll('.portal-grid .portal-card')],modules=cards.map(card=>card.dataset.module),routes=cards.map(card=>card.dataset.route);if(cards.length!==4||modules.join(',')!=='warehouse,reports,monitoring,profile')throw Error('four module cards contract');if(routes.join(',')!=='warehouse/overview,reports/daily,monitoring/monitoring,profile/profile')throw Error('module card routes');if(cards.find(card=>card.dataset.module==='monitoring').textContent.match(/Проблемы|События/))throw Error('warehouse labels leaked into monitoring card');return true})()`);
  await evaluate(`document.querySelector('[data-module-open="monitoring"]').click()`);
  await waitFor(`document.getElementById('monitoring').classList.contains('active')&&location.hash==='#monitoring/monitoring'`);
  await evaluate(`(()=>{const root=document.getElementById('monitoring');if(!/в разработке/i.test(root.textContent)||/Проблемы|События/.test(root.textContent)||root.querySelector('button'))throw Error('monitoring must be placeholder only');return true})()`);
  visited.monitoring=true;await clickText('ODE');await assertHome('home after monitoring card');visited.odeHome=true;
  await installAutoConfirm();
  await evaluate(`document.querySelector('[data-module-open="warehouse"]').click()`);
  await waitFor(`document.getElementById('overview').classList.contains('active')&&location.hash==='#warehouse/overview'`);
  visited.warehouse=true;await clickText('Принять оборудование'); await clickText('Сканировать оборудование');
  await clickText('К способам приемки');
  await waitFor(`document.querySelector('#receipt .scenario-stage').hidden&&!document.querySelector('#receipt .scenario-cards').hidden`);
  await clickText('Сканировать оборудование');
  for (const text of ['Оборудование','Сервер','Dell','PowerEdge R650']) await clickText(text);
  await evaluate(`if(wShelf.options.length<2)wShelf.add(new Option('A-01','A-01'));if(wDc.options.length<2)wDc.add(new Option('Ixcellerate','Ixcellerate'));wShelf.selectedIndex=1;wDc.selectedIndex=1;document.querySelector('.wizard-next').click()`);
  try { await waitFor(`document.getElementById('receiptScanner')&&!document.getElementById('receiptScanner').closest('.scanner-box').hidden&&document.getElementById('receipt').classList.contains('active')`); }
  catch (error) { throw new Error(error.message+' '+JSON.stringify(await evaluate(`({heading:document.querySelector('.wizard-shell h2')?.textContent,status:status?.textContent,uiError:interfaceError?.textContent,form:!!document.getElementById('scanReceiptForm'),scanner:!!document.getElementById('receiptScanner'),scannerHidden:document.getElementById('receiptScanner')?.closest('.scanner-box').hidden,receiptClass:document.getElementById('receipt')?.className,stageHidden:document.querySelector('#receipt .scenario-stage')?.hidden,stage:document.querySelector('#receipt .scenario-stage')?.innerText})`))); }
  for (const serial of Object.values(serials)) await scanInto('receiptScanner',serial);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===3&&JSON.parse(localStorage.getItem('ode_receipt_draft')).rows.length===3&&document.getElementById('scanReceiptCount').textContent.startsWith('3 ')`);
  await scanInto('receiptScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===3&&document.getElementById('status').textContent==='Этот S/N уже находится в текущем списке'&&document.querySelector('#scanReceiptBody tr.scan-duplicate')&&document.activeElement===document.getElementById('receiptScanner')`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('.scanner-delete').click();return true})()`);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem('ode_receipt_draft')).rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})&&document.activeElement===document.getElementById('receiptScanner')&&window.__confirmCalls===0`);
  await scanInto('receiptScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===3`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('input[type=checkbox]').click();document.getElementById('deleteSelectedReceipts').click();return true})()`);
  await waitFor(`window.__confirmCalls===1&&document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem('ode_receipt_draft')).rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})`);
  await evaluate(`(()=>{const draft=JSON.parse(localStorage.getItem('ode_receipt_draft'));draft.rows.push({...draft.rows[0],serial_number:draft.rows[0].serial_number.toLowerCase()});localStorage.setItem('ode_receipt_draft',JSON.stringify(draft));location.reload()})()`);await sleep(750);
  await waitFor(`document.getElementById('receipt').classList.contains('active')&&document.getElementById('activeDrafts')&&!document.getElementById('activeDrafts').hidden&&typeof state!=='undefined'&&state.current_user?.first_name`);
  await installAutoConfirm();
  await evaluate(`(()=>{const box=[...document.querySelectorAll('#activeDrafts div')].find(item=>item.textContent.includes('Черновик приемки'));[...box.querySelectorAll('button')].find(button=>button.textContent.includes('Вернуться')).click();return true})()`);
  await waitFor(`document.getElementById('receipt').classList.contains('active')&&document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2&&JSON.parse(localStorage.getItem('ode_receipt_draft')).rows.length===2&&document.activeElement===document.getElementById('receiptScanner')`);
  visited.reloadAndBack=true;
  await evaluate(`document.getElementById('confirmScanReceipts').click()`);
  await waitFor(`!localStorage.getItem('ode_receipt_draft')&&state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.a)})&&state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.c)})&&!state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.b)})`);
  for(const serial of receiptTemps)await scanInto('receiptScanner',serial);
  await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===2`);
  await evaluate(`document.getElementById('clearScannedReceipts').click()`);
  await waitFor(`window.__confirmCalls===1&&!localStorage.getItem('ode_receipt_draft')&&document.querySelector('#scanReceiptBody .scanner-empty')&&document.activeElement===document.getElementById('receiptScanner')`);
  await scanInto('receiptScanner',serials.b);await waitFor(`document.querySelectorAll('#scanReceiptBody tr[data-scan-serial]').length===1`);
  await evaluate(`document.getElementById('confirmScanReceipts').click()`);
  await waitFor(`!localStorage.getItem('ode_receipt_draft')&&state.recent_receipts.some(row=>row.serial_number===${JSON.stringify(serials.b)})`);
  await assertClean('receipt draft deletion');visited.receipt=true;
  await evaluate(`document.getElementById('globalSearchTrigger').click()`);
  await waitFor(`document.getElementById('globalSearchModal').classList.contains('show')&&document.activeElement===document.getElementById('globalSearch')`);
  await evaluate(`globalSearch.value='stale query';globalSearch.dispatchEvent(new Event('input',{bubbles:true}));globalSearch.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  await waitFor(`!document.getElementById('globalSearchModal').classList.contains('show')&&document.activeElement===document.getElementById('globalSearchTrigger')&&!document.getElementById('globalSearchResults').children.length`);
  await evaluate(`document.getElementById('globalSearchTrigger').click();globalSearch.value=${JSON.stringify(serials.b)};globalSearch.dispatchEvent(new Event('input',{bubbles:true}))`);
  await waitFor(`document.querySelector('.global-search-result')?.textContent.includes(${JSON.stringify(serials.b)})`);
  await evaluate(`document.querySelector('.global-search-result').click()`);
  await waitFor(`document.getElementById('positionModal').classList.contains('show')&&document.getElementById('positionDetails').textContent.includes(${JSON.stringify(serials.b)})`);
  await waitFor(`document.querySelector('#positionDetails .equipment-inventory-assignment input[name="inventory_number"]')!==null`);
  await evaluate(`(()=>{const form=document.querySelector('#positionDetails .equipment-inventory-assignment');form.elements.namedItem('inventory_number').value=${JSON.stringify(assignedInventory)};form.requestSubmit();return true})()`);
  await waitFor(`document.getElementById('positionDetails').textContent.includes(${JSON.stringify(assignedInventory)})&&!document.querySelector('#positionDetails .equipment-inventory-assignment')&&document.getElementById('positionHistory').textContent.includes('EQUIPMENT_INVENTORY_NUMBER_ASSIGNED')`);
  await assertClean('equipment inventory number assignment');
  visited.globalSearch = true;
  await evaluate(`history.back()`);
  await waitFor(`!document.getElementById('positionModal').classList.contains('show')`);
  await clickText('Расход');await waitFor(`document.getElementById('issue').classList.contains('active')`);await clickText('Сканировать оборудование');
  await waitFor(`document.getElementById('issueScanner')&&!document.getElementById('issueScanner').closest('.scanner-box').hidden`);
  await installAutoConfirm();
  await evaluate(`(()=>{const form=document.getElementById('scanIssueForm'),task=form.elements.namedItem('task_type');if(![...task.options].some(option=>option.value==='ПНР'))task.add(new Option('ПНР','ПНР'));task.value='ПНР';form.elements.namedItem('task_number').value='SMOKE-'+${JSON.stringify(smokeToken)};return true})()`);
  for(const serial of Object.values(serials))await scanInto('issueScanner',serial);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===3&&JSON.parse(localStorage.getItem('ode_issue_draft')).rows.length===3`);
  await scanInto('issueScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===3&&document.getElementById('status').textContent==='Этот S/N уже находится в текущем списке'&&document.querySelector('#scanIssueBody tr.scan-duplicate')`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanIssueBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('.scanner-delete').click();return true})()`);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem('ode_issue_draft')).rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})&&window.__confirmCalls===0&&document.activeElement===document.getElementById('issueScanner')`);
  await scanInto('issueScanner',serials.b);await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===3`);
  await evaluate(`(()=>{const key=${JSON.stringify(serials.b.toLowerCase())},row=[...document.querySelectorAll('#scanIssueBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('input[type=checkbox]').click();document.getElementById('deleteSelectedIssues').click();return true})()`);
  await waitFor(`window.__confirmCalls===1&&document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===2&&!JSON.parse(localStorage.getItem('ode_issue_draft')).rows.some(row=>row.serial_number===${JSON.stringify(serials.b)})`);
  await evaluate(`location.reload()`);await sleep(750);await waitFor(`document.getElementById('issue')?.classList.contains('active')&&document.getElementById('activeDrafts')&&!document.getElementById('activeDrafts').hidden&&typeof state!=='undefined'&&state.current_user?.first_name`);await installAutoConfirm();
  await evaluate(`(()=>{const box=[...document.querySelectorAll('#activeDrafts div')].find(item=>item.textContent.includes('Черновик расхода'));[...box.querySelectorAll('button')].find(button=>button.textContent.includes('Вернуться')).click();return true})()`);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===2&&JSON.parse(localStorage.getItem('ode_issue_draft')).rows.length===2&&document.activeElement===document.getElementById('issueScanner')`);
  await evaluate(`document.getElementById('confirmScanIssues').click()`);
  await waitFor(`!localStorage.getItem('ode_issue_draft')&&!scanDraftRuntime.issue.confirming`);
  await evaluate(`Promise.all(${JSON.stringify(Object.values(serials))}.map(serial=>fetch('/api/position-search?'+new URLSearchParams({query:serial})).then(response=>response.json()))).then(results=>{const balances=results.map(result=>Number(result.rows[0]?.balance));if(balances[0]!==0||balances[1]!==1||balances[2]!==0)throw Error('issue draft balances '+balances.join(','));return true})`);
  await scanInto('issueScanner',serials.b);await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===1`);await scanInto('issueScanner',serials.b);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===1&&document.getElementById('status').textContent==='Этот S/N уже находится в текущем списке'`);
  await scanInto('issueScanner',unknownIssue);await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===2`);
  await evaluate(`(()=>{const key=${JSON.stringify(unknownIssue.toLowerCase())},row=[...document.querySelectorAll('#scanIssueBody tr[data-scan-serial]')].find(item=>item.dataset.scanSerial===key);row.querySelector('.scanner-delete').click();return true})()`);
  await waitFor(`document.querySelectorAll('#scanIssueBody tr[data-scan-serial]').length===1&&!JSON.parse(localStorage.getItem('ode_issue_draft')).rows.some(row=>row.serial_number===${JSON.stringify(unknownIssue)})`);
  await evaluate(`loadAll()`);await waitFor(`!state.problems.unmatched_issues.some(row=>row.serial_number===${JSON.stringify(unknownIssue)})`);
  await evaluate(`document.getElementById('clearScannedIssues').click()`);
  await waitFor(`window.__confirmCalls===1&&!localStorage.getItem('ode_issue_draft')&&document.querySelector('#scanIssueBody .scanner-empty')&&document.activeElement===document.getElementById('issueScanner')`);
  await assertClean('issue draft deletion');visited.issue=true;
  await clickText('Баланс'); await waitFor(`document.getElementById('balance').classList.contains('active')`); await assertClean('balance'); visited.balance = true;
  await waitFor(`document.querySelectorAll('#balanceKpis .kpi-card').length===6`);
  await evaluate(`(()=>{const card=[...document.querySelectorAll('#balanceKpis .kpi-card')].find(x=>x.textContent.includes('Серверы'));if(!card)throw Error('balance card: Серверы');card.click()})()`);
  await waitFor(`document.querySelector('#balanceKpis .kpi-card.active')?.textContent.includes('Серверы')`);
  await evaluate(`document.querySelector('#balanceKpis .reset-balance').click()`);
  await waitFor(`document.querySelector('#balanceKpis .kpi-card.active')===null`);
  await evaluate(`document.getElementById('balanceQuery').value=${JSON.stringify(serials.b)};document.getElementById('balanceQuery').dispatchEvent(new Event('input',{bubbles:true}))`);
  await waitFor(`[...document.querySelectorAll('#balanceBody tr')].some(row=>row.textContent.includes(${JSON.stringify(serials.b)})&&row.querySelector('button'))`);
  await evaluate(`(()=>{const row=[...document.querySelectorAll('#balanceBody tr')].find(item=>item.textContent.includes(${JSON.stringify(serials.b)})),button=row&&[...row.querySelectorAll('button')].find(x=>x.textContent.includes('Открыть карточку'));if(!button)throw Error('position card button missing for expected S/N');button.click()})()`);
  await waitFor(`document.getElementById('positionModal').classList.contains('show')&&document.getElementById('positionDetails').textContent.includes(${JSON.stringify(serials.b)})`);
  await evaluate(`closePositionCard()`);
  await evaluate(`document.getElementById('balanceQuery').value='';document.getElementById('balanceQuery').dispatchEvent(new Event('input',{bubbles:true}))`);
  await evaluate(`(()=>{const labels=[...document.querySelectorAll('#subnav .subtab')].map(x=>x.textContent.trim());if(!labels.includes('Проблемы')||!labels.includes('События'))throw Error('warehouse Problems/Events navigation missing');return true})()`);
  await clickText('Проблемы'); await waitFor(`currentSection==='warehouse'&&document.getElementById('problems').classList.contains('active')`); await assertClean('warehouse problems');
  await clickText('События'); await waitFor(`currentSection==='warehouse'&&document.getElementById('journal').classList.contains('active')`);
  await waitFor(`document.querySelector('#operationBody')&&document.querySelector('.history-summary')&&(document.querySelectorAll('#operationBody tr').length>0||document.querySelector('.history-empty'))`);
  await evaluate(`(()=>{const input=document.querySelector('#journal .history-search');if(!input)throw Error('history search missing');input.value=${JSON.stringify(serials.b)};input.dispatchEvent(new Event('input',{bubbles:true}))})()`);
  await waitFor(`document.querySelectorAll('#operationBody tr').length>0||document.querySelector('.history-empty')`);
  await evaluate(`(()=>{const reset=document.querySelector('#journal .history-reset');if(!reset)throw Error('history reset missing');reset.click()})()`);
  await waitFor(`document.querySelector('#journal .history-search').value===''`);
  await assertClean('history'); visited.history = true;
  await clickText('Профиль'); await waitFor(`document.getElementById('profile').classList.contains('active')&&document.getElementById('shiftProfileCard')&&!document.getElementById('shiftProfileCard').hidden`); await assertClean('profile'); visited.profile = true;
  await clickText('Обновить'); await sleep(300); await assertClean('refresh');
  await clickText('ODE'); await assertHome('ODE home after profile');
  await evaluate(`document.querySelector('[data-module-open="reports"]').click()`); await waitFor(`document.getElementById('daily').classList.contains('active')&&location.hash==='#reports/daily'`);
  await evaluate(`(()=>{const f=document.getElementById('dailyForm'),today=new Date().toISOString().slice(0,10);f.elements.namedItem('date').value=today;f.requestSubmit()})()`);
  await waitFor(`document.querySelectorAll('#dailyBody tr').length>0`);
  await clickText('Логи работ'); await waitFor(`document.getElementById('worklogs').classList.contains('active')`);
  await evaluate(`(()=>{const f=document.getElementById('workLogForm');f.elements.namedItem('work_date').value=new Date().toISOString().slice(0,10);const source=f.elements.namedItem('task_source'),type=f.elements.namedItem('task_type'),status=f.elements.namedItem('status');if(source.options.length>1)source.selectedIndex=1;if(type.options.length>1)type.selectedIndex=1;f.elements.namedItem('task_number').value='SMOKE-WORKLOG-1';f.elements.namedItem('description').value='Проверка ReportsFacade read API';if(status.options.length>1)status.selectedIndex=1;f.elements.namedItem('comment').value='smoke';f.requestSubmit()})()`);
  await sleep(400);
  await evaluate(`document.getElementById('workLogFilter').requestSubmit()`);
  await waitFor(`document.getElementById('workLogBody').textContent.includes('SMOKE-WORKLOG-1')`);
  await waitFor(`document.getElementById('exportWorkLogs').href.includes('/export/work-logs.csv')`);
  await clickText('Еженедельный'); await waitFor(`document.getElementById('weekly').classList.contains('active')`);
  await evaluate(`(()=>{const f=document.getElementById('weeklyForm'),today=new Date().toISOString().slice(0,10);f.elements.namedItem('start_date').value=today;f.elements.namedItem('end_date').value=today;f.requestSubmit()})()`);
  await waitFor(`document.querySelectorAll('#weeklyCards .card').length>0&&document.getElementById('downloadWeekly').onclick`);
  await assertClean('reports'); visited.reports = true; await clickText('ODE'); await assertHome('ODE home after reports');
  await clickText('Профиль'); await waitFor(`document.getElementById('profile').classList.contains('active')`); await assertClean('profile card'); await clickText('ODE'); await assertHome('ODE home after profile card');
  await evaluate(`document.querySelector('[data-module-open="warehouse"]').click()`);await waitFor(`document.getElementById('overview').classList.contains('active')`);await clickText('Поставки'); await assertClean('deliveries');
  await evaluate(`(()=>{const row=document.querySelector('#deliveryBody tr');const button=row&&[...row.querySelectorAll('button')].find(x=>x.textContent.includes('Открыть'));if(button)button.click();return true})()`);
  await assertClean('delivery optional card');
  await clickText('Инвентаризация'); await assertClean('inventory'); await clickText('ODE'); await assertHome('ODE home final');
  await clickText('Сменить инженера'); await waitFor(`document.getElementById('login')!==null`);
  await evaluate(`document.getElementById('mode').click();document.querySelector('[name=email]').value='lokolis';document.querySelector('[name=password]').value='lokolis';document.getElementById('login').requestSubmit()`);
  await waitFor(`document.querySelector('.home-screen.active')!==null&&typeof state!=='undefined'&&state.current_user?.role==='admin'`);
  await waitFor(`document.querySelector('.admin-entry')&&!document.querySelector('.admin-entry').hidden&&document.querySelector('.admin-entry').getClientRects().length>0`);
  await evaluate(`document.querySelector('.admin-entry').click()`);
  await waitFor(`document.getElementById('admin').classList.contains('active')`);
  await waitFor(`document.getElementById('userBody').textContent.includes('lokolis')`);
  await evaluate(`fetch('/api/admin').then(async response=>{if(!response.ok)throw Error('admin API '+response.status);const body=await response.json();if(!body.users?.some(user=>user.email==='lokolis'))throw Error('admin API user missing');return true})`);
  await assertClean('admin users');
  await clickText('Резервные копии');
  await waitFor(`document.getElementById('admin').classList.contains('active')&&(document.querySelectorAll('#backupBody tr').length>0||document.getElementById('backupBody').textContent.includes('Резервных копий нет'))`);
  await assertClean('admin backups');
  await clickText('Журнал действий');
  await waitFor(`document.getElementById('admin').classList.contains('active')&&(document.querySelectorAll('#auditBody tr').length>0||document.getElementById('auditBody').textContent.includes('Записей аудита нет'))`);
  await assertClean('admin audit');
  await clickText('Сменить пароль');
  await waitFor(`document.getElementById('profile').classList.contains('active')&&document.getElementById('passwordForm')&&!document.getElementById('passwordForm').closest('.box').hidden`);
  await assertClean('admin password profile');
  visited.administration = true;
  await clickText('ODE'); await assertHome('ODE home after admin');
  const result = await evaluate(`({home:document.querySelector('#home.active')!==null,errors:document.getElementById('interfaceError')?.textContent||'',receiptSaved:${JSON.stringify(Object.values(serials))}.every(serial=>state.recent_receipts.some(row=>row.serial_number===serial)),issueBalances:${JSON.stringify(Object.values(serials))}.map(serial=>Number(state.balance.find(row=>row.serial_number===serial)?.balance)),draftsCleared:!localStorage.getItem('ode_receipt_draft')&&!localStorage.getItem('ode_issue_draft'),adminVisible:!document.querySelector('.admin-entry').hidden,balanceCards:document.querySelectorAll('#balanceKpis .kpi-card').length})`);
  result.noConsoleErrors = runtimeErrors.length === 0;
  result.noWindowErrors = !result.errors;
  result.noUnhandledRejections = !result.errors && runtimeErrors.length === 0;
  result.noResourceErrors = resourceErrors.length === 0;
  result.noHttpErrors = httpErrors.length === 0;
  result.noApi500 = apiErrors.length === 0;
  result.visited = visited;
  console.log(JSON.stringify(result)); ws.close();
  if (!result.home || result.errors || !result.receiptSaved || result.issueBalances.join(',')!=='0,1,0' || !result.draftsCleared || !result.adminVisible || result.balanceCards!==6 || !result.noConsoleErrors || !result.noResourceErrors || !result.noHttpErrors || !result.noApi500 || Object.values(visited).some(x=>!x)) process.exitCode = 1;
})().catch(e => { console.error(e); process.exit(1); });
